### ISSUE TITLE
Problem connection GIT

### ISSUE THREAD

**Issue by LuisMirth** [kpalang/git-ext#2]
Hi,
I see the version History tab, but in the settings the connection with GIT does not appear. Do I need something else or is your plugging enough?

**Comment by LuisMirth** [comment]
Hi,
I'm trying to connect to git, but I can't get the code to upload.
Do I have to have any special configuration, library or other configuration?
Thanks

**Comment by jonbartels** [comment]
What have you tried?
What errors are you getting if any?
Show your configs **but hide any passwords or usernames**
Which tab do you see?
Show the "Extensions" list from MC.

**Comment by LuisMirth** [comment]
Hi,
I'm trying to configure the Git extension so I can have version control.
I don't see any type of error in the logs, and the connection test is correct but in the TEST branch I don't see the changes.
Configuration GIT:
![Captura](https://user-images.githubusercontent.com/99884933/155477563-b0f1a1ee-ecb1-4ca4-a981-bc4fd3bf7a85.PNG)
![Captura3](https://user-images.githubusercontent.com/99884933/155478253-9baf658f-8b1b-41a6-9b8c-8b1ecb23bf80.PNG)
Extension:
![Captura2](https://user-images.githubusercontent.com/99884933/155477682-b7cedcb3-28e8-4144-a2e8-a9a544c0084c.PNG)

**Comment by LuisMirth** [comment]
Now the connection doesn't work.
Give a time out.
![image](https://user-images.githubusercontent.com/99884933/156772380-0005a288-b008-4463-bbaf-35118533c38c.png)

**Comment by kpalang** [comment]
Hello! I thought I would come by and explain the situation a little.
I have abandoned this fork and am working on a completely new implementation. I apologize for not clarifying this anywhere.
If you would like to stay up to date with the progress of the new plugin, feel free to join [Mirth Slack](https://forums.mirthproject.io/forum/mirth-connect/support/15720-join-the-mirth-connect-slack-channel) (if you haven't already) and ask me at @CreepySheep.

I'm also closing this issue and archiving the repository.
